# Generated by Django 2.2.7 on 2019-12-01 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=501)),
                ('fullname', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='plan', max_length=250)),
                ('year', models.IntegerField(default=2019)),
                ('document', models.FileField(default='settings.MEDIA_ROOT/plan.docx', upload_to='media')),
                ('ucheb_r_1_p', models.FloatField(default=0)),
                ('ucheb_r_2_p', models.FloatField(default=0)),
                ('ucheb_med_r_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('ucheb_med_r_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('nir_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('nir_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('vr_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('vr_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('inr_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('inr_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('dr_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
                ('dr_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete='cascade', primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dolzhnost', models.CharField(blank=True, max_length=500)),
                ('fullname', models.CharField(blank=True, max_length=250)),
                ('stepen', models.CharField(blank=True, max_length=250)),
                ('role', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepods', to='plan.Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='DocInfo',
            fields=[
                ('shapka', models.CharField(blank=True, max_length=250)),
                ('fionach', models.CharField(blank=True, max_length=250)),
                ('data', models.CharField(blank=True, max_length=250)),
                ('na_kakoygod', models.IntegerField(blank=True, default=2019)),
                ('na_kakoygod1', models.IntegerField(blank=True, default=2020)),
                ('fio', models.CharField(blank=True, max_length=250)),
                ('dolznost', models.CharField(blank=True, max_length=250)),
                ('stavka', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('uchzv', models.CharField(blank=True, max_length=250)),
                ('uchst', models.CharField(blank=True, max_length=250)),
                ('visluga', models.IntegerField(blank=True, default=0)),
                ('kafedra', models.CharField(blank=True, max_length=250)),
                ('plan', models.OneToOneField(on_delete='cascade', primary_key=True, related_name='shapka', serialize=False, to='plan.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='VR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(blank=True, max_length=500)),
                ('srok', models.CharField(blank=True, max_length=500)),
                ('otmetka', models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500)),
                ('year', models.IntegerField(default=2019)),
                ('polugodie', models.IntegerField(default=1)),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dubl_to_in', models.BooleanField(default=False)),
                ('vid', models.CharField(blank=True, max_length=500)),
                ('srok', models.CharField(blank=True, max_length=500)),
                ('otmetka', models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500)),
                ('year', models.IntegerField(default=2019)),
                ('polugodie', models.IntegerField(default=1)),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umr', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('leccii', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('seminar', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('practici_v_gruppe', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('practici_v_podgruppe', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('krugliy_stol', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('konsultacii_pered_ekzamenom', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('tekushie_konsultacii', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('vneauditor_chtenie', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('rucovodstvo_practikoy', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('rucovodstvo_VKR', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('rucovodstvo_kursovoy', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('proverka_auditor_KR', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('proverka_dom_KR', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('proverka_practicuma', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('proverka_lab', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('priem_zashit_practic', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('zacheti_ust', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('zacheti_pism', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('priem_vstupit', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('ekzamenov', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('priem_GIA', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('priem_kandidtskih', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('rucovodstvo_adunctami', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('ucheb_nagruzka', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('auditor_nagruzka', models.FloatField(blank=True, default=0, validators=[plan.models.validate_decimals])),
                ('year', models.IntegerField(blank=True, default=2019)),
                ('polugodie', models.IntegerField(blank=True, default=1)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predmets', to='plan.Kafedra')),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predmets', to='plan.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='prepod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plan.Profile'),
        ),
        migrations.CreateModel(
            name='NIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(blank=True, max_length=500)),
                ('srok', models.CharField(blank=True, max_length=500)),
                ('otmetka', models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500)),
                ('year', models.IntegerField(default=2019)),
                ('polugodie', models.IntegerField(default=1)),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nir', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Nagruzka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2019)),
                ('document', models.FileField(default='settings.MEDIA_ROOT/plan.docx', upload_to='files')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nagruzki', to='plan.Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='INR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(blank=True, max_length=500)),
                ('srok', models.CharField(blank=True, max_length=500)),
                ('otmetka', models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500)),
                ('year', models.IntegerField(default=2019)),
                ('polugodie', models.IntegerField(default=1)),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inr', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(blank=True, max_length=500)),
                ('srok', models.CharField(blank=True, max_length=500)),
                ('otmetka', models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500)),
                ('year', models.IntegerField(default=2019)),
                ('polugodie', models.IntegerField(default=1)),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr', to='plan.Profile')),
            ],
        ),
    ]
