# Generated by Django 2.1.5 on 2019-07-05 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1999)),
                ('polugodie', models.IntegerField(default=1)),
                ('srok', models.CharField(max_length=50)),
                ('otmetka', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='INR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1999)),
                ('polugodie', models.IntegerField(default=1)),
                ('srok', models.CharField(max_length=50)),
                ('otmetka', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nagruzka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1999)),
                ('document', models.FileField(default='settings.MEDIA_ROOT/plan.docx', upload_to='media')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nagruzki', to='plan.Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='NIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1999)),
                ('polugodie', models.IntegerField(default=1)),
                ('srok', models.CharField(max_length=50)),
                ('otmetka', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='plan', max_length=50)),
                ('year', models.IntegerField(default=1999)),
                ('document', models.FileField(default='settings.MEDIA_ROOT/plan.docx', upload_to='media')),
                ('ucheb_r_1_p', models.FloatField(default=0)),
                ('ucheb_r_2_p', models.FloatField(default=0)),
                ('ucheb_med_r_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('ucheb_med_r_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('nir_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('nir_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('vr_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('vr_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('inr_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('inr_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('dr_1_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
                ('dr_2_p', models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена')], default='Выполнена', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('leccii', models.IntegerField(blank=True, default=0)),
                ('seminar', models.IntegerField(blank=True, default=0)),
                ('practici_v_gruppe', models.IntegerField(blank=True, default=0)),
                ('practici_v_podgruppe', models.IntegerField(blank=True, default=0)),
                ('krugliy_stol', models.IntegerField(blank=True, default=0)),
                ('konsultacii_pered_ekzamenom', models.IntegerField(blank=True, default=0)),
                ('tekushie_konsultacii', models.IntegerField(blank=True, default=0)),
                ('vneauditor_chtenie', models.IntegerField(blank=True, default=0)),
                ('rucovodstvo_practikoy', models.IntegerField(blank=True, default=0)),
                ('rucovodstvo_VKR', models.IntegerField(blank=True, default=0)),
                ('rucovodstvo_kursovoy', models.IntegerField(blank=True, default=0)),
                ('proverka_auditor_KR', models.IntegerField(blank=True, default=0)),
                ('proverka_dom_KR', models.IntegerField(blank=True, default=0)),
                ('proverka_practicuma', models.IntegerField(blank=True, default=0)),
                ('proverka_lab', models.IntegerField(blank=True, default=0)),
                ('priem_zashit_practic', models.IntegerField(blank=True, default=0)),
                ('zacheti_ust', models.IntegerField(blank=True, default=0)),
                ('zacheti_pism', models.IntegerField(blank=True, default=0)),
                ('priem_vstupit', models.IntegerField(blank=True, default=0)),
                ('ekzamenov', models.IntegerField(blank=True, default=0)),
                ('priem_GIA', models.IntegerField(blank=True, default=0)),
                ('priem_kandidtskih', models.IntegerField(blank=True, default=0)),
                ('rucovodstvo_adunctami', models.IntegerField(blank=True, default=0)),
                ('ucheb_nagruzka', models.IntegerField(blank=True, default=0)),
                ('auditor_nagruzka', models.IntegerField(blank=True, default=0)),
                ('year', models.IntegerField(blank=True, default=1999)),
                ('polugodie', models.IntegerField(blank=True, default=1)),
                ('status', models.BooleanField(blank=True, default=False)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predmets', to='plan.Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete='cascade', primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dolzhnost', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepods', to='plan.Kafedra')),
            ],
        ),
        migrations.CreateModel(
            name='UMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1999)),
                ('polugodie', models.IntegerField(default=1)),
                ('srok', models.CharField(max_length=50)),
                ('otmetka', models.CharField(max_length=50)),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umr', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='VR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1999)),
                ('polugodie', models.IntegerField(default=1)),
                ('srok', models.CharField(max_length=50)),
                ('otmetka', models.CharField(max_length=50)),
                ('prepodavatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr', to='plan.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='predmet',
            name='prepodavatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predmets', to='plan.Profile'),
        ),
        migrations.AddField(
            model_name='plan',
            name='prepod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plan.Profile'),
        ),
        migrations.AddField(
            model_name='nir',
            name='prepodavatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nir', to='plan.Profile'),
        ),
        migrations.AddField(
            model_name='inr',
            name='prepodavatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inr', to='plan.Profile'),
        ),
        migrations.AddField(
            model_name='dr',
            name='prepodavatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr', to='plan.Profile'),
        ),
    ]
