# Generated by Django 2.1.5 on 2019-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagruzka',
            name='document',
            field=models.FileField(default='settings.MEDIA_ROOT/plan.docx', upload_to='files'),
        ),
    ]
