# Generated by Django 2.2.7 on 2019-12-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docinfo',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shapka', serialize=False, to='plan.Plan'),
        ),
    ]
