# Generated by Django 2.2.7 on 2019-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20191201_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dr',
            name='srok',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='dr',
            name='vid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='inr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=1000),
        ),
        migrations.AlterField(
            model_name='inr',
            name='srok',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='inr',
            name='vid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='nir',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=1000),
        ),
        migrations.AlterField(
            model_name='nir',
            name='srok',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='nir',
            name='vid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dolzhnost',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='umr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=1000),
        ),
        migrations.AlterField(
            model_name='umr',
            name='srok',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='umr',
            name='vid',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vr',
            name='srok',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vr',
            name='vid',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
