# Generated by Django 2.2.3 on 2019-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20190705_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
