# Generated by Django 2.2.3 on 2019-07-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_kafedra_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
