# Generated by Django 2.2.7 on 2019-12-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20191201_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docinfo',
            name='na_kakoygod',
            field=models.IntegerField(blank=True, default=2019, null=True),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='na_kakoygod1',
            field=models.IntegerField(blank=True, default=2020, null=True),
        ),
    ]
