# Generated by Django 2.2.7 on 2019-12-05 23:07

from django.db import migrations, models
import plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20191205_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='leccii',
            field=models.FloatField(blank=True, default=0, null=True, validators=[plan.models.validate_decimals]),
        ),
    ]
