# Generated by Django 2.2.3 on 2019-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
