# Generated by Django 2.2.7 on 2019-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20191205_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagruzka',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
