# Generated by Django 2.2.3 on 2019-07-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_profile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stepen',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
