# Generated by Django 2.2.7 on 2019-12-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_nagruzka_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagruzka',
            name='status',
            field=models.CharField(choices=[('Планируемая', 'Планируемая'), ('Фактическая', 'Планируемая')], default=' ', max_length=20),
        ),
    ]
