# Generated by Django 2.2.3 on 2019-07-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_profile_stepen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='otmetka',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dr',
            name='srok',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dr',
            name='vid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inr',
            name='otmetka',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inr',
            name='srok',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inr',
            name='vid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='fullname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='nir',
            name='otmetka',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='nir',
            name='srok',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='nir',
            name='vid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='plan', max_length=250),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dolzhnost',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stepen',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='umr',
            name='otmetka',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='umr',
            name='srok',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='umr',
            name='vid',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vr',
            name='otmetka',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vr',
            name='srok',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vr',
            name='vid',
            field=models.CharField(max_length=250),
        ),
    ]
