# Generated by Django 2.2.7 on 2019-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20191211_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagruzka',
            name='status',
            field=models.CharField(choices=[('Планируемая', 'Планируемая'), ('Фактическая', 'Фактическая')], default='Планируемая', max_length=20),
        ),
    ]
