# Generated by Django 2.2.3 on 2019-08-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20190715_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocInfo',
            fields=[
                ('shapka', models.TextField()),
                ('fionach', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('na_kakoygod', models.TextField()),
                ('fio', models.TextField()),
                ('dolznost', models.TextField()),
                ('kafedra', models.TextField()),
                ('plan', models.OneToOneField(on_delete='cascade', primary_key=True, related_name='shapka', serialize=False, to='plan.Plan')),
            ],
        ),
    ]
