# Generated by Django 2.2.3 on 2019-09-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_docinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docinfo',
            name='data',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='dolznost',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='fio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='fionach',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='kafedra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='na_kakoygod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='shapka',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
