# Generated by Django 2.2.3 on 2019-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20190917_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='inr',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='nir',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='plan',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='year',
            field=models.IntegerField(blank=True, default=2019),
        ),
        migrations.AlterField(
            model_name='umr',
            name='year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='vr',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
