# Generated by Django 2.2.7 on 2020-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_mesyac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
