# Generated by Django 2.2.7 on 2019-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20191013_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='otmetka',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dr',
            name='srok',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dr',
            name='vid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inr',
            name='otmetka',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inr',
            name='srok',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inr',
            name='vid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nir',
            name='otmetka',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nir',
            name='srok',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nir',
            name='vid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dolzhnost',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='umr',
            name='otmetka',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='umr',
            name='srok',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='umr',
            name='vid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vr',
            name='otmetka',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vr',
            name='srok',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vr',
            name='vid',
            field=models.TextField(),
        ),
    ]
