# Generated by Django 2.2.7 on 2019-11-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20191106_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='docinfo',
            name='stavka',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='docinfo',
            name='uchzv',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='docinfo',
            name='visluga',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='data',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='dolznost',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='fio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='fionach',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='kafedra',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='na_kakoygod',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='shapka',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dr',
            name='otmetka',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dr',
            name='srok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dr',
            name='vid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inr',
            name='otmetka',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inr',
            name='srok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inr',
            name='vid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='name',
            field=models.CharField(max_length=501),
        ),
        migrations.AlterField(
            model_name='nir',
            name='otmetka',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='nir',
            name='srok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='nir',
            name='vid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dolzhnost',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='umr',
            name='otmetka',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='umr',
            name='srok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='umr',
            name='vid',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vr',
            name='otmetka',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vr',
            name='srok',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vr',
            name='vid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
