# Generated by Django 2.2.7 on 2019-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_auto_20191128_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='dr_1_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dr_2_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='inr_1_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='inr_2_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nir_1_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nir_2_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ucheb_med_r_1_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ucheb_med_r_2_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vr_1_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vr_2_p',
            field=models.CharField(choices=[('Выполнена', 'Выполнена'), ('Выполнена', 'Выполнена частично'), ('Выполнена', 'Не выполнена'), (' ', ' ')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='umr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500),
        ),
    ]
