# Generated by Django 2.2.7 on 2019-11-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_auto_20191129_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500),
        ),
        migrations.AlterField(
            model_name='inr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500),
        ),
        migrations.AlterField(
            model_name='nir',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='auditor_nagruzka',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='ekzamenov',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='konsultacii_pered_ekzamenom',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='krugliy_stol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='leccii',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='practici_v_gruppe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='practici_v_podgruppe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_GIA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_kandidtskih',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_vstupit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_zashit_practic',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_auditor_KR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_dom_KR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_lab',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_practicuma',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_VKR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_adunctami',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_kursovoy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_practikoy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='seminar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='tekushie_konsultacii',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='ucheb_nagruzka',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='vneauditor_chtenie',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='zacheti_pism',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='zacheti_ust',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vr',
            name='otmetka',
            field=models.CharField(blank=True, default='___________ Протокол №__ от __.__.20__', max_length=500),
        ),
    ]
