# Generated by Django 2.2.7 on 2019-11-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_auto_20191129_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='auditor_nagruzka',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='ekzamenov',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='konsultacii_pered_ekzamenom',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='krugliy_stol',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='leccii',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='practici_v_gruppe',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='practici_v_podgruppe',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_GIA',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_kandidtskih',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_vstupit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='priem_zashit_practic',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_auditor_KR',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_dom_KR',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_lab',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='proverka_practicuma',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_VKR',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_adunctami',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_kursovoy',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='rucovodstvo_practikoy',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='seminar',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='tekushie_konsultacii',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='ucheb_nagruzka',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='vneauditor_chtenie',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='zacheti_pism',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='zacheti_ust',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
