# Generated by Django 2.2.6 on 2020-06-10 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='URR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsh', models.IntegerField(default=0)),
                ('sootn', models.IntegerField(default=0)),
                ('zansprakt', models.IntegerField(default=0)),
                ('viezdsprakt', models.IntegerField(default=0)),
                ('ppsfp', models.IntegerField(default=0)),
                ('ppsdr', models.IntegerField(default=0)),
                ('vneaudotor', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urr', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PCR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otkr', models.IntegerField(default=0)),
                ('kontrud', models.IntegerField(default=0)),
                ('kontrneud', models.IntegerField(default=0)),
                ('sriv', models.IntegerField(default=0)),
                ('opozdanie', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcr', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ORMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruksec', models.IntegerField(default=0)),
                ('rukpredmsek', models.IntegerField(default=0)),
                ('rabotaruk', models.IntegerField(default=0)),
                ('rabotachlen', models.IntegerField(default=0)),
                ('rukkafnach', models.IntegerField(default=0)),
                ('rukkafzam', models.IntegerField(default=0)),
                ('bestprepodmir', models.IntegerField(default=0)),
                ('bestprepodrus', models.IntegerField(default=0)),
                ('bestprepodreg', models.IntegerField(default=0)),
                ('bestprepodunik', models.IntegerField(default=0)),
                ('uchastiebestprepodmir', models.IntegerField(default=0)),
                ('uchastiebestprepodrus', models.IntegerField(default=0)),
                ('uchastiebestprepodreg', models.IntegerField(default=0)),
                ('uchastiebestprepodunik', models.IntegerField(default=0)),
                ('ekspert', models.IntegerField(default=0)),
                ('metodkonk1', models.IntegerField(default=0)),
                ('metodkonk2', models.IntegerField(default=0)),
                ('metodkonk3', models.IntegerField(default=0)),
                ('profmaster', models.IntegerField(default=0)),
                ('podgsbornmir', models.IntegerField(default=0)),
                ('podgsbornrus', models.IntegerField(default=0)),
                ('podgsbornreg', models.IntegerField(default=0)),
                ('podgsbornunik', models.IntegerField(default=0)),
                ('vulkan', models.IntegerField(default=0)),
                ('plenar', models.IntegerField(default=0)),
                ('obrprogramma', models.IntegerField(default=0)),
                ('proverkaf', models.IntegerField(default=0)),
                ('inpectunik', models.IntegerField(default=0)),
                ('resocenki1', models.IntegerField(default=0)),
                ('resocenki6', models.IntegerField(default=0)),
                ('resocenki11', models.IntegerField(default=0)),
                ('resocenki16', models.IntegerField(default=0)),
                ('resocenki26', models.IntegerField(default=0)),
                ('inovac', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ormr', to='plan.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='MRR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razr1', models.IntegerField(default=0)),
                ('razr2', models.IntegerField(default=0)),
                ('razr3', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Profile')),
            ],
        ),
    ]
